"""add_audio_duration_to_usage_logs

Revision ID: 89984d63a2e6
Revises: a4b2d9e31582
Create Date: 2026-04-03 23:01:43.531431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89984d63a2e6'
down_revision: Union[str, Sequence[str], None] = 'a4b2d9e31582'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('whisper_instances')
    op.add_column('usage_logs', sa.Column('audio_duration_ms', sa.Integer(), nullable=True))
    op.drop_column('whisper_transcription_jobs', 'instance_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whisper_transcription_jobs', sa.Column('instance_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('usage_logs', 'audio_duration_ms')
    op.create_table('whisper_instances',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('executable_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('model_path', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('host', sa.TEXT(), server_default=sa.text("'127.0.0.1'::text"), autoincrement=False, nullable=False),
    sa.Column('port', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('n_threads', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('n_processors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('beam_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('best_of', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audio_ctx', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('auto_start', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('auto_restart', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('max_restart_attempts', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False),
    sa.Column('startup_timeout', sa.INTEGER(), server_default=sa.text('60'), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('created_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('updated_at', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('whisper_instances_pkey')),
    sa.UniqueConstraint('name', name=op.f('whisper_instances_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
