"""add ubatch_size to llama_instances

Revision ID: b610b56a9879
Revises: dfe44a893793
Create Date: 2026-04-02 12:59:43.899478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b610b56a9879'
down_revision: Union[str, Sequence[str], None] = 'dfe44a893793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llama_instances', sa.Column('ubatch_size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llama_instances', 'ubatch_size')
    # ### end Alembic commands ###
