"""add_manually_stopped_to_llama_instances

Revision ID: def3052b24be
Revises: 89984d63a2e6
Create Date: 2026-04-17 16:09:08.424916

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'def3052b24be'
down_revision: Union[str, Sequence[str], None] = '89984d63a2e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llama_instances', sa.Column('manually_stopped', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llama_instances', 'manually_stopped')
    # ### end Alembic commands ###
